# Generated by Django 5.1.4 on 2025-02-17 16:08

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.TextField(max_length=100)),
                ('address_line1', models.CharField(blank=True, max_length=1500, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=1500, null=True)),
                ('address_line3', models.CharField(blank=True, max_length=1500, null=True)),
                ('contact_no', models.TextField(max_length=10)),
                ('landline_contact', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=25)),
                ('duration', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=300)),
                ('no_of_tests', models.IntegerField()),
                ('study_material', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveSmallIntegerField(help_text='Age should be between 21 and 40.', validators=[django.core.validators.MinValueValidator(21), django.core.validators.MaxValueValidator(40)])),
                ('educational_qualification', models.CharField(default='', max_length=255)),
                ('contact_number', models.CharField(help_text='Enter a Valid Mobile Number', max_length=10)),
                ('address_of_residence', models.CharField(max_length=255)),
                ('pincode', models.CharField(blank='False', max_length=150, null='False')),
                ('interested_course_Course', models.CharField(choices=[('tnpsc', 'TNPSC'), ('upsc', 'UPSC'), ('tnusrb', 'TNUSRB'), ('ssb', 'SSB'), ('rrb', 'RRB'), ('app', 'APP')], max_length=255)),
                ('how_do_you_know_us', models.CharField(choices=[('friends', 'Friends'), ('family', 'Family'), ('newspaper', 'Newspaper'), ('tv ads', 'TV Ads'), ('posters', 'Posters'), ('others', 'Others')], max_length=255)),
                ('enquired', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='', max_length=255)),
                ('last_follow_up', models.DateTimeField(auto_now=True)),
                ('next_follow_up', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=800)),
                ('product_img', models.ImageField(upload_to='materials/')),
                ('product_type', models.CharField(choices=[('book', 'Book'), ('tnbook', 'TNBook'), ('tnusrb', 'tnusrb'), ('ssb', 'ssb'), ('rrb', 'rrb'), ('ssc', 'ssc'), ('app', 'app')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myhome.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhome.product')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhome.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('forum_desc', models.CharField(max_length=500)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank='True', related_name='participants', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhome.topic')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('forums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhome.forums')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delivery_Address', models.CharField(blank='False', max_length=255, null='False')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Zipcode', models.IntegerField(blank='False', null='False')),
                ('phone_number', models.IntegerField(blank='False', null='False')),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('CARD', 'Credit/Debit Card'), ('UPI', 'UPI Apps')], default='COD', max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='orders', to='myhome.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhome.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhome.product')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('classroom', models.CharField(blank=True, max_length=10, null=True)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myhome.courses')),
                ('period_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_1_timetables', to='myhome.subject')),
                ('period_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_2_timetables', to='myhome.subject')),
                ('period_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_3_timetables', to='myhome.subject')),
                ('period_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_4_timetables', to='myhome.subject')),
                ('period_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_5_timetables', to='myhome.subject')),
                ('period_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_6_timetables', to='myhome.subject')),
                ('period_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_7_timetables', to='myhome.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
