# Generated by Django 5.1.4 on 2025-01-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='address',
        ),
        migrations.AddField(
            model_name='contactus',
            name='address_line1',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='address_line2',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='address_line3',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
