# Generated by Django 5.1.4 on 2025-02-17 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0002_delete_timetable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('classroom', models.CharField(blank=True, max_length=10, null=True)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myhome.courses')),
                ('period_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_1_timetables', to='myhome.subject')),
                ('period_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_2_timetables', to='myhome.subject')),
                ('period_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_3_timetables', to='myhome.subject')),
                ('period_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_4_timetables', to='myhome.subject')),
                ('period_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_5_timetables', to='myhome.subject')),
                ('period_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_6_timetables', to='myhome.subject')),
                ('period_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_7_timetables', to='myhome.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
