# Generated by Django 5.1.4 on 2025-01-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0002_remove_contactus_address_contactus_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=800)),
                ('product_img', models.ImageField(upload_to='materials/')),
                ('product_type', models.CharField(choices=[('book', 'Book'), ('tnbook', 'TNBook'), ('tnusrb', 'tnusrb'), ('ssb', 'ssb'), ('rrb', 'rrb'), ('ssc', 'ssc'), ('app', 'app')], max_length=50)),
            ],
        ),
    ]
