# Generated by Django 5.1.4 on 2025-01-22 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0003_alter_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhome.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhome.product')),
            ],
        ),
    ]
