# Generated by Django 5.1.4 on 2025-01-20 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0004_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_line_1', models.CharField(max_length=255)),
                ('Address_line_2', models.CharField(max_length=255)),
                ('Address_line_3', models.CharField(max_length=255)),
                ('Zipcode', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('payment_method', models.CharField(max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('items', models.ManyToManyField(to='myhome.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
