# Generated by Django 5.1.4 on 2025-01-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Address_line_2',
            field=models.CharField(blank='True', max_length=255, null='True'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Address_line_3',
            field=models.CharField(blank='True', max_length=255, null='True'),
        ),
    ]
