# Generated by Django 5.1.6 on 2025-03-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0006_alter_userprofile_address_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='encrypted_username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
