# Generated by Django 5.1.6 on 2025-03-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0007_order_encrypted_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='encrypted_product_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
